---
abstract: 'Network Portal API'
author:
  - 'Broadbean <drop@broadbean.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NetPortal-API
requires:
  Dancer: 1.3110
  Dancer::Test: 0
version: 0.001
